version: '3.8'

services:
  # Nginx 服务
  nginx:
    image: nginx:alpine
    container_name: web-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
      - nodejs
    networks:
      - app-network
    restart: unless-stopped

  # PHP-FPM 服务
  php:
    image: php:8.2-fpm-alpine
    container_name: web-php
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./logs/php:/var/log/php
    environment:
      - PHP_MEMORY_LIMIT=128M
      - UPLOAD_MAX_FILESIZE=32M
      - POST_MAX_SIZE=32M
    networks:
      - app-network
    restart: unless-stopped

  # Node.js 服务
  nodejs:
    image: node:18-alpine
    container_name: web-nodejs
    volumes:
      - ./node:/app
      - ./logs/node:/var/log/node
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    command: >
      sh -c "npm install && npm start"

  # MySQL 数据库服务
  mysql:
    image: arm64v8/mariadb:10.11
    container_name: web-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped
    # MariaDB 的优化参数
    command:
      - --innodb-buffer-pool-size=32M
      - --key-buffer-size=4M
      - --query-cache-size=4M
      - --max-connections=50
      - --performance-schema=OFF

  # adminer (可选web数据库管理)
  adminer:
    image: adminer:4.8.1
    container_name: web-adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local